### PR TITLE
Documentation for Aggregate Queries

### LINKED ISSUE #29: Aggregate Queries in SOQL Datatable - Add README documentation
https://github.com/tsalb/lwc-utils/pull/24 is a really neat feature I'd love to have documented, we should get the README updated with some usage steps and instructions for all to see.

Not that important yet to create a PR for it, but we can use this thread to dump pictures and hash out what kind of examples to show users this is now possible (and any limitations should be called out as well).

FYI @jamessimone

### PR DESCRIPTION
**Pull request by jamessimone**
Initial commit with documentation for aggregate queries, fixes #29

### CODE REVIEW

**Comment by tsalb** [comment]
Gonna get to this one in the evening. I want to try out the aggregate queries itself and see what my own learning pains were and what I think could be added to the README because of that.

First hand experience!

**Comment by jamessimone** [comment]
No rush!

**Comment by tsalb** [comment]
@jamessimone There we go. I added some recipes on a new `Aggregate SOQL Datatable` tab in the `LWC Utils` app.

If you get a chance, feel free to play with it - otherwise can you do a sanity check for me and rebuild branch into a new scratch org to see if everything works?

**Comment by jamessimone** [comment]
@tsalb nice, really loving those changes!

**Comment by jamessimone** [comment]
@tsalb spun up a fresh scratch org and deployed with no issues. Took a look through, the new recipe flexipage for the Aggregate SOQL Datatable looks good and is a nice touch. LGTM!

**Pull request merged**
