### PR TITLE
Modified readme to recommend installing recipes in a scratch org (as opposed to sandbox)

### PR DESCRIPTION
**Pull request by solo-1234**

### CODE REVIEW

**Comment by solo-1234** [comment]
Not sure if I did this correctly, any feedback is welcome.

**Comment by tsalb** [comment]
Almost there! You can actually pull the wiki files too, though I am not 100% sure if you can include them in the same PR (that's your homework)

I'd like to see all following changes in the wiki as well, for example:

https://github.com/tsalb/lwc-utils/wiki/Installation

So, one (or two) action items:
- Amend this PR to include wiki edits
- Create a second PR which includes wiki edits, add comment (to either this or new PR) linking both

Then, I will double check the PR and make sure we address these verbiage changes simultaneously.

**Comment by solo-1234** [comment]
It appears that wiki edits cannot be included in a PR...
https://github.community/t/how-to-fork-a-wiki-and-send-a-pr/2006

**Comment by tsalb** [comment]
That is unfortunate, as a workaround maybe we can do this:

Can you please comb through the wiki and let me know if there are any other references to “sandbox” and we can change that verbiage to “scratch org”.

I’m looking for a bullet list of both pages and content that will have to change. Basically, the format should be easy enough for me to execute since we can’t do it in a PR sadly…

**Comment by solo-1234** [comment]
Do you want to change all to scratch org, or add that scratch orgs are recommended over sandboxes?

In some places I'd keep sandbox (like the installation links...)

**Comment by tsalb** [comment]
Everything should be scratch org, all references sandboxes are deprecated as of this PR to avoid potential issues.

The developer using this lib will know, based on pre-req, to know how to spin up scratch orgs.

FWIW, I never used sandboxes to test the recipes. This PR will make the signaling very clear that scratch orgs are the way to go (alignment to lwc-recipes from Salesforce themselves).

**Comment by solo-1234** [comment]
Right but for installing core, I'd do it in a sandbox first to test things before installing it in prod

**Comment by tsalb** [comment]
Yea, but that is not my problem ;)

That’s up to the developer on how to install - this repo no longer recommends the action forward for you.

**Comment by solo-1234** [comment]
For sure - but I'd keep the sandbox install link for that purpose, personally.

**Comment by tsalb** [comment]
The intention here is to make it a little harder to install on a sandbox so only users who know what to do with the package ids know what to do with them.

Think of it like an intentional barrier to entry, one that is more targeted for devs.

As this is my preference, I will align to the instructions I have set up on my corporate version of this lib.

**Comment by solo-1234** [comment]
Got it

**Comment by tsalb** [comment]
For the purposes of this PR, feel free to omit the content for the wiki as I have some ideas for it.

What I need from you to unblock this PR are a list of wiki pages (as a sanity check) on where we would need to make verbiage updates. The content of the change I will noodle on, but it’s good to link specific pages to this PR so we can trace for posterity.

**Comment by solo-1234** [comment]
github search found two pages with the word `sandbox`
https://github.com/tsalb/lwc-utils/wiki/Installation
https://github.com/tsalb/lwc-utils/wiki/Getting-Started

**Comment by tsalb** [comment]
The following pages have been amended as part of this PR:

- https://github.com/tsalb/lwc-utils/wiki/Installation
- https://github.com/tsalb/lwc-utils/wiki/Getting-Started

**Pull request merged**
